baseURL = 'https://atearin.space/'
languageCode = 'en-us'
title = 'A Tear in Space'
theme = 'nightfall'
paginate = 5

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "adam"
hostname = "atearin.space"
author.name = "A Tear in Space"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/akilleen"

[[params.social]]
key = 1
name = "mastodon"
url = "https://todon.eu/@atearinspace"
rel = "me"

[[params.social]]
key = 2
name = "bandcamp"
url = "https://bandcamp.com/atearinspace"