# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Hugo
        run: |
          cd /tmp
          wget https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_0.96.0_Linux-64bit.deb
          sudo dpkg -i /tmp/hugo_0.96.0_Linux-64bit.deb

      - name: Install and configure neocities gem
        run: |
          sudo gem install neocities
          mkdir -p ~/.config/neocities
          echo -n ${{ secrets.NEOCITIES_KEY }} > ~/.config/neocities/config

      - name: Run Hugo and Deploy
        run: |
          cd atearinspace
          git submodule init
          git submodule update
          hugo
          neocities push public
