name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          submodules: true
          persist-credentials: false

      - name: Install Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2
        with:
          hugo-version: 0.161.1
          extended: true

      - name: Run Hugo
        run: hugo --logLevel info

      - name: Deploy via WebDAV
        uses: XPH0816/webdav-deploy-action@dacd363983664b11c42c281bf5f0d6668b5b302a # v0.3
        with:
          url: ${{ secrets.WEBDAV_URL }}
          username: ${{ secrets.WEBDAV_USER }}
          password: ${{ secrets.WEBDAV_PASSWORD }}
          local: public
          remote: ${{ secrets.WEBDAV_REMOTE_FOLDER }}
            
      #- name: Deploy to S3
      #  uses: jakejarvis/s3-sync-action@master
      #  with:
      #    args: --acl public-read --follow-symlinks --delete
      #  env:
      #    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      #    SOURCE_DIR: public
      #- name: Invalidate Cache
      #  uses: awact/cloudfront-action@master
      #  env:
      #    SOURCE_PATH: '/*'
      #    AWS_REGION: 'us-east-1'
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      #    DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}

