# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main, use-marketplace-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
        
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.97.0

      - name: Run Hugo and Deploy
        run: |
          ls -l 
          pwd
          cd atearinspace
          hugo
      
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_KEY }}
          cleanup: false
          dist_dir: public

